spring:
  application:
    name: jasony-registry
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN
  boot:
    admin:
      client:
        url: http://localhost:8761
server:
  port: 8761

logging:
  file:
    name: target/switch-registry.log

eureka:
  instance:
    appname: jasony-registry
    instanceId: jasonyRegistry:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://admin:${spring.security.user.password:admin}@localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000
  dashboard:
    path: /registry
management:
  endpoints:
    web:
      exposure:
        include: '*'
      #include: ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump']
  endpoint:
    health:
      show-details: always
debug: true
